(ns kotoba.ifc
  (:require [ifc.core :as impl]))

(def schema impl/schema)
(def contract-version impl/contract-version)
(def entity-types impl/entity-types)
(def exchange-document impl/exchange-document)
(def write-spf impl/write-spf)
(def rewrite-spf impl/rewrite-spf)
(def semantic-fingerprint impl/semantic-fingerprint)
(def roundtrip-report impl/roundtrip-report)
(def corpus-report impl/corpus-report)
(def perturb-geometry impl/perturb-geometry)
(def edit-first-geometry impl/edit-first-geometry)
(def schema-native-geometry-edit? impl/schema-native-geometry-edit?)
(def read-spf impl/read-spf)
(def engineering-to-map-coordinate impl/engineering-to-map-coordinate)
(def map-to-engineering-coordinate impl/map-to-engineering-coordinate)
(def model-to-map-coordinate impl/model-to-map-coordinate)
(def map-to-model-coordinate impl/map-to-model-coordinate)
